
import argparse
import json
import os
import re
import sys
from pathlib import Path


def read_text(path: str) -> str:
    p = Path(path)
    if not p.exists():
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)
    return p.read_text(encoding='utf-8')


def parse_panels(content: str):
    panels = []
    current_page = None
    current_panel = None
    current_section = None
    buffer = []
    in_fence = False
    fence_indent = 0
    lines = content.splitlines()
    for line in lines:
        page_m = re.match(r'^##\s+Page\s+(\d+)$', line)
        panel_m = re.match(r'^###\s+Panel\s+(\d+)$', line)

        if page_m:
            if current_panel is not None:
                panels.append({'page': current_page, 'panel': current_panel, 'fields': dict(buffer)})
                buffer = []
            current_page = int(page_m.group(1))
            current_panel = None
            current_section = None
            in_fence = False
            continue

        if panel_m:
            if current_panel is not None:
                panels.append({'page': current_page, 'panel': current_panel, 'fields': dict(buffer)})
                buffer = []
            current_panel = int(panel_m.group(1))
            current_section = None
            in_fence = False
            continue

        if current_panel is not None:
            stripped = line.rstrip('\n')
            if stripped.strip().startswith('```'):
                in_fence = not in_fence
                if in_fence:
                    fence_indent = len(line) - len(line.lstrip())
                # keep fence markers out of field text
                continue
            if in_fence:
                last_key = buffer[-1][0] if buffer else current_section
                content_line = line[fence_indent:] if line.startswith(' ' * fence_indent) else line
                if buffer:
                    buffer[-1] = (last_key, buffer[-1][1] + '\n' + content_line.rstrip())
                continue
            field_m = re.match(r'^\*\*(.+?)\*\*\s*[:：]\s*(.*)$', line)
            if field_m:
                key = field_m.group(1).strip()
                val = field_m.group(2).strip()
                current_section = key
                buffer.append((key, val))
            elif current_section and line.startswith('  '):
                last_key = buffer[-1][0] if buffer else current_section
                buffer[-1] = (last_key, buffer[-1][1] + '\n' + line.strip())
            elif line.strip() == '':
                current_section = None

    if current_panel is not None:
        panels.append({'page': current_page, 'panel': current_panel, 'fields': dict(buffer)})
    return panels


def load_style_guide(style_guide_path: str):
    """Load positive/negative prompts plus optional consistency notes from style_guide.md.

    Supports both:
    - fenced blocks: **正向提示词**：```text ... ```
    - heading blocks: ## 正向提示词\n...
    Also reads optional ## 角色视觉指纹 / ## 风格说明 for consistency locking.
    """
    text = read_text(style_guide_path)
    positive = ''
    negative = ''
    consistency = ''

    # Fenced format used in some examples
    pos_m = re.search(r'正向(?:提示词)?[：:]\s*```(?:text)?\n(.*?)```', text, re.S)
    neg_m = re.search(r'反向(?:提示词)?[：:]\s*```(?:text)?\n(.*?)```', text, re.S)
    if pos_m:
        positive = pos_m.group(1).strip()
    if neg_m:
        negative = neg_m.group(1).strip()

    # Heading format generated by init_project.py
    if not positive:
        pos_m = re.search(r'##\s*正向提示词\s*\n(.+?)(?:\n##\s|\Z)', text, re.S)
        if pos_m:
            positive = pos_m.group(1).strip()
    if not negative:
        neg_m = re.search(r'##\s*反向提示词\s*\n(.+?)(?:\n##\s|\Z)', text, re.S)
        if neg_m:
            negative = neg_m.group(1).strip()

    # Fallback: first fenced block as positive
    if not positive:
        any_pos = re.search(r'```(?:text)?\n(.*?)```', text, re.S)
        if any_pos:
            positive = any_pos.group(1).strip()
    # Optional consistency locks: character fingerprints and style notes.
    chunks = []
    for heading in ('角色视觉指纹', '风格说明'):
        m = re.search(r'##\s*' + re.escape(heading) + r'\s*\n(.+?)(?:\n##\s|\Z)', text, re.S)
        if m:
            clean = re.sub(r'\s+', ' ', m.group(1)).strip()
            if clean:
                chunks.append(clean)
    consistency = ' '.join(chunks)

    return positive, negative, consistency



def extract_positive_from_ai_prompt(ai_text: str) -> str:
    """Return only the positive prompt part from a Panel AI 提示词 field."""
    if not ai_text:
        return ''
    text = ai_text.strip()
    # Strip explicit negative section if present in flattened fenced text.
    text = re.split(r'反向[：:]?', text, maxsplit=1)[0].strip()
    # If prompt blocks were flattened as positive line + negative quality line, remove common negative prefix.
    lines = []
    for line in text.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.lower().startswith(('worst quality', 'low quality', 'blurry', 'bad anatomy')):
            continue
        lines.append(s)
    return ', '.join(lines).strip()

def clean_prompt_parts(*parts):
    """Merge prompt fragments, remove negative terms accidentally copied into positive prompts."""
    negative_markers = {
        'photorealistic', '3d render', 'oil painting', 'messy anatomy', 'extra fingers',
        'blurry', 'readable text', 'watermark', 'logo', 'worst quality', 'low quality',
        'bad anatomy', 'deformed', 'extra limbs'
    }
    seen = set()
    out = []
    for part in parts:
        for chunk in re.split(r'[,，]\s*', part or ''):
            s = chunk.strip()
            if not s:
                continue
            low = s.lower()
            if low in negative_markers:
                continue
            if low.startswith(('反向', 'negative')):
                continue
            if low not in seen:
                seen.add(low)
                out.append(s)
    return ', '.join(out)


def render_output(project_name, episode_label, panels, positive_style, negative_style, panel_range):
    start = 1
    end = None
    if panel_range and panel_range.lower() != 'all':
        m = re.match(r'(\d+)-(\d+)$', panel_range)
        if m:
            start = int(m.group(1))
            end = int(m.group(2))
    scenes = []
    scene_index = 0
    for panel in panels:
        p = panel['panel']
        if p < start or (end is not None and p > end):
            continue
        fields = panel['fields']
        visual = fields.get('画面', '')
        composition = fields.get('构图', '')
        ai = extract_positive_from_ai_prompt(fields.get('AI 提示词', ''))
        # Keep dialogue out of the image-generation prompt. Text is overlaid later by overlay_comic_text.py
        # so the model only draws clean manga art with empty bubble space.
        narration = fields.get('旁白', '')
        if narration.strip() == '无':
            narration = ''

        scene_index += 1
        scenes.append({
            'scene_id': f"scene_{scene_index:02d}",
            'panel': p,
            'page': panel['page'],
            'duration': 5,
            'narration': narration,
            'visual_description': visual,
            'prompt': ai,
            'camera': composition,
        })
    return scenes


def to_storyboard_md(project_name, episode_label, scenes, positive_style, negative_style, consistency_style=''):
    lines = []
    lines.append(f"# {project_name} - {episode_label} 可渲染输入")
    lines.append('')
    lines.append(f"**来源项目**：{project_name}")
    lines.append(f"**剧集**：{episode_label}")
    lines.append(f"**镜头数**：{len(scenes)}")
    lines.append('')
    lines.append('---')
    lines.append('')
    for scene in scenes:
        lines.append("## 镜头 " + str(int(scene['scene_id'].split("_")[-1])))
        lines.append('')
        if scene.get('duration'):
            lines.append(f"**时长**：{scene['duration']}秒")
            lines.append('')
        if scene.get('visual_description'):
            lines.append(f"**画面**：{scene['visual_description']}")
            lines.append('')
        if scene.get('camera'):
            lines.append(f"**镜头**：{scene['camera']}")
            lines.append('')
        if scene.get('narration'):
            lines.append(f"**旁白**：{scene['narration']}")
            lines.append('')
        if positive_style:
            lines.append('**正向提示词**：')
            lines.append('```text')
            prompt = clean_prompt_parts(
                positive_style,
                consistency_style,
                'CONSISTENCY LOCK: same character design, same face, same hairstyle, same outfit, same manga line style, same screentone density across all panels',
                'single clean manga panel, no text inside the artwork, leave empty space for speech bubbles, readable sequential action',
                scene.get('visual_description') or '',
                scene.get('camera') or '',
                scene.get('prompt') or ''
            )
            lines.append(prompt)
            lines.append('```')
            lines.append('')
        if negative_style:
            lines.append('**反向提示词**：')
            lines.append('```text')
            lines.append(negative_style)
            lines.append('```')
            lines.append('')
        lines.append('---')
        lines.append('')
    lines.append('*由 export_for_render.py 自动生成*')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Export comic episode panels to story-renderer input script')
    parser.add_argument('episode', help='Episode markdown file path')
    parser.add_argument('--project-dir', required=True, help='Project directory')
    parser.add_argument('--style-guide', required=True, help='style_guide.md path')
    parser.add_argument('--panels', default='all', help='Panel range like 1-10 or all')
    parser.add_argument('--output', help='Output path override')
    args = parser.parse_args()

    content = read_text(args.episode)
    panels = parse_panels(content)
    if not panels:
        print('ERROR: no Page/Panel blocks found in episode', file=sys.stderr)
        sys.exit(1)

    positive, negative, consistency = load_style_guide(args.style_guide)

    episode_label = Path(args.episode).stem
    project_name = Path(args.project_dir).name

    scenes = render_output(project_name, episode_label, panels, positive, negative, args.panels)
    md = to_storyboard_md(project_name, episode_label, scenes, positive, negative, consistency)

    out = args.output
    if not out:
        render_dir = Path(args.project_dir) / 'render_input'
        render_dir.mkdir(parents=True, exist_ok=True)
        safe_label = re.sub(r'[^A-Za-z0-9_-]+', '_', episode_label)
        out = str(render_dir / f"{safe_label}_render.md")

    Path(out).write_text(md, encoding='utf-8')
    print(json.dumps({
        'status': 'ok',
        'project': project_name,
        'episode': episode_label,
        'panels_parsed': len(panels),
        'scenes': len(scenes),
        'output': out,
    }, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
