#!/usr/bin/env python3
"""Stitch comic page PNGs into a complete localized long-strip chapter.

Input: project/comic_pages/*.png generated by compose_manga_pages.py.
Output: project/localized/<project>_完整汉化长图.png plus optional sliced pages.
"""
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


def find_font():
    for c in ['/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc','/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf']:
        if Path(c).exists(): return c
    return None


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('project_dir')
    ap.add_argument('--output-dir', default=None)
    ap.add_argument('--gap', type=int, default=24)
    ap.add_argument('--max-slice-height', type=int, default=0, help='If >0, also slice long image into chunks of this height')
    args=ap.parse_args()
    project=Path(args.project_dir)
    pages=sorted((project/'comic_pages').glob('*.png'))
    if not pages:
        raise SystemExit('no comic_pages/*.png found')
    out_dir=Path(args.output_dir) if args.output_dir else project/'localized'
    out_dir.mkdir(parents=True, exist_ok=True)
    imgs=[Image.open(p).convert('RGB') for p in pages]
    width=max(i.width for i in imgs)
    margin=36
    title_h=110
    gap=args.gap
    total_h=title_h + margin*2 + sum(i.height for i in imgs) + gap*(len(imgs)-1)
    canvas=Image.new('RGB',(width+margin*2,total_h),(250,252,255))
    draw=ImageDraw.Draw(canvas)
    font_path=find_font()
    title_font=ImageFont.truetype(font_path,42) if font_path else ImageFont.load_default()
    small=ImageFont.truetype(font_path,24) if font_path else ImageFont.load_default()
    title=project.name.replace('_',' ')
    draw.text((margin,28), title, font=title_font, fill=(15,23,42))
    draw.text((margin,78), f'完整汉化长图 · 共 {len(imgs)} 页', font=small, fill=(100,116,139))
    y=title_h
    for idx,im in enumerate(imgs,1):
        x=margin+(width-im.width)//2
        # subtle paper shadow/border
        draw.rectangle((x-2,y-2,x+im.width+2,y+im.height+2), fill=(226,232,240))
        canvas.paste(im,(x,y))
        y += im.height + gap
    name=f'{project.name}_完整汉化长图.png'
    out=out_dir/name
    canvas.save(out, quality=95)
    slices=[]
    if args.max_slice_height and total_h > args.max_slice_height:
        h=args.max_slice_height
        for i,top in enumerate(range(0,total_h,h),1):
            crop=canvas.crop((0,top,canvas.width,min(top+h,total_h)))
            sp=out_dir/f'{project.name}_完整汉化长图_part{i:02d}.png'
            crop.save(sp,quality=95)
            slices.append(str(sp))
    print({'project':str(project),'pages':len(pages),'output':str(out),'size':canvas.size,'slices':slices})

if __name__=='__main__': main()
