#!/usr/bin/env python3
"""Validate light novel project/chapters generated by comic-script-generator mode 6."""
import argparse, json, re
from pathlib import Path
from difflib import SequenceMatcher

TEMPLATE_PATTERNS = [
    '第1段里', '第2段里', '第3段里', '第4段里', '第5段里', '第6段里', '第7段里', '第8段里',
    '【长篇深化段落】', '表面上这只是一次普通的相遇', '越往前走，越能看见它和主线之间细密的缝线',
    '这段插曲结束以后', '真正漫长的故事，总会在看似已经结束的地方留下回音'
]

def normalize_para(s: str) -> str:
    s = re.sub(r'<!--.*?-->', '', s, flags=re.S)
    s = re.sub(r'[\s，。！？、：“”"\'‘’（）()《》【】\-—…]+', '', s)
    s = re.sub(r'第\d+[章节段]', '第N', s)
    return s.strip()

def repetition_stats(text: str):
    paras = [p.strip() for p in re.split(r'\n\s*\n+', text) if len(normalize_para(p)) >= 40]
    norms = [normalize_para(p) for p in paras]
    seen = {}
    duplicates = 0
    near_duplicates = 0
    for n in norms:
        if n in seen:
            duplicates += 1
        seen[n] = seen.get(n, 0) + 1
    # Check adjacent-ish similarity in a bounded way to avoid O(n^2) explosion
    for i, a in enumerate(norms):
        for b in norms[i+1:i+8]:
            if len(a) < 60 or len(b) < 60:
                continue
            if SequenceMatcher(None, a, b).ratio() >= 0.88:
                near_duplicates += 1
                break
    denom = max(1, len(norms))
    return {
        'paragraphs': len(norms),
        'duplicate_paragraphs': duplicates,
        'near_duplicate_paragraphs': near_duplicates,
        'duplicate_rate': round((duplicates + near_duplicates) / denom, 3),
    }


def validate_chapter(path: Path, min_chars=2500, min_dialogues=8, max_duplicate_rate=0.18):
    text = path.read_text(encoding='utf-8', errors='ignore')
    issues=[]
    title = re.search(r'^#\s+(.+)', text, re.M)
    if not title: issues.append('missing H1 title')
    chars = len(re.sub(r'\s+', '', text))
    if chars < min_chars: issues.append(f'too short: {chars} chars < {min_chars}')
    dialogues = len(re.findall(r'^「.+?」——.+$', text, re.M))
    if dialogues < min_dialogues: issues.append(f'too few dialogues: {dialogues} < {min_dialogues}')
    illust = len(re.findall(r'<!--\s*ILLUST_\d+\s*-->', text))
    if illust < 3: issues.append(f'too few illustration markers: {illust} < 3')
    forbidden = ['**格子**', '**构图**', '**转场**', '### Panel', '## Page', '| 字段 | 内容 |']
    found=[x for x in forbidden if x in text]
    if found: issues.append('contains comic technical markers: '+', '.join(found))
    if '> 无' in text or '\n无\n' in text: issues.append('contains raw empty marker: 无')
    template_hits=[x for x in TEMPLATE_PATTERNS if x in text]
    if template_hits: issues.append('contains template/repetitive phrases: '+', '.join(template_hits[:6]))
    rep = repetition_stats(text)
    if rep['duplicate_rate'] > max_duplicate_rate:
        issues.append(f'too repetitive: duplicate_rate {rep["duplicate_rate"]} > {max_duplicate_rate}')
    return {'file': path.name, 'passed': not issues, 'issues': issues, 'stats': {'chars': chars, 'dialogues': dialogues, 'illustrations': illust, **rep}}


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('target', help='chapter markdown file or project directory')
    ap.add_argument('--min-chars', type=int, default=2500)
    ap.add_argument('--min-dialogues', type=int, default=8)
    ap.add_argument('--max-duplicate-rate', type=float, default=0.18)
    ap.add_argument('--max-adjacent-similarity', type=float, default=0.82)
    args=ap.parse_args()
    p=Path(args.target)
    files=[]
    if p.is_dir():
        files=sorted((p/'light_novel').glob('ln*.md')) if (p/'light_novel').exists() else sorted(p.glob('ln*.md'))
    else:
        files=[p]
    results=[validate_chapter(f,args.min_chars,args.min_dialogues,args.max_duplicate_rate) for f in files]
    adjacent=[]
    if len(files) > 1:
        prev_txt = None
        prev_name = None
        for f in files:
            txt = normalize_para(f.read_text(encoding='utf-8', errors='ignore'))[:6000]
            if prev_txt:
                sim = SequenceMatcher(None, prev_txt, txt).ratio()
                if sim > args.max_adjacent_similarity:
                    adjacent.append({'a': prev_name, 'b': f.name, 'similarity': round(sim,3)})
            prev_txt = txt
            prev_name = f.name
    if adjacent:
        results.append({'file': '__project_similarity__', 'passed': False, 'issues': [f'adjacent chapters too similar: {adjacent[:5]}'], 'stats': {'adjacent_failures': len(adjacent)}})
    passed=all(r['passed'] for r in results) and bool(files)
    print(json.dumps({'passed':passed,'count':len(files),'results':results},ensure_ascii=False,indent=2))
    raise SystemExit(0 if passed else 1)

if __name__=='__main__': main()
